GET http://localhost:3002/api/notes/68700281acb7837f4dd6e4f6

###
DELETE http://localhost:3002/api/notes/
Content-Type: application/json

{ 
    "content": "Chunky donkey"
    
}

###
GET http://localhost:3002/api/notes/

###
GET https://fso-twwa.onrender.com/api/notes/1

##